# Generated by Django 4.2 on 2024-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_work_district'),
        ('account', '0006_alter_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcategory',
            field=models.ManyToManyField(related_name='users', to='work.subcategory'),
        ),
    ]
