# Generated by Django 4.2 on 2024-01-04 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='FISH')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter in the format +998901234567', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
        ),
    ]
