# Generated by Django 4.2 on 2024-01-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_employer'),
        ('work', '0002_alter_work_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='account.employer', verbose_name='Ish beruvchi'),
        ),
    ]
