# Generated by Django 4.2 on 2024-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='work',
            name='subcategory',
            field=models.ManyToManyField(related_name='works', to='work.subcategory', verbose_name='SubCategory'),
        ),
    ]
